scheme: zenodo
formatSetting: application/json
description: a metadata for citation metadata, used in zenodo

mapping:
   - target_key: //titles/0/title
     source_key: title
   - target_key: //creators/0/name
     source_key: contributors[*].contributorName
     priority: 2
   - target_key: //creators/0/affiliation/0/name
     source_key: contributors[*].contributorAffiliation
   - target_key: //contributors/0/name
     source_key: contact[*].contactName
     priority: 2
   - target_key: //creators/0/nameIdentifiers/0/nameIdentifier
     source_key: contributors[*].contributorId
#   - target_key: datasetContactEmail
#     source_key: contact[*].contactEmail
   - target_key: //subjects/0/subject
     source_key: keywords[*]
     priority: 2
   - target_key: //relatedItems/0/relatedItemType
     source_key: ["relatedId[*].relationType", "relatedId[*].id", "relatedId[*].comment"]
     join_symbol: " "
     type: merge
   - target_key: //contributors/0/name
     source_key: contributors[*].contributorName
   - target_key: //contributors/0/contributorType
     source_key: ccontributors[*].contributorRole
