scheme: zenodo
targetSystem: zenodo
formatSetting: application/json
description: a metadata for citation metadata, used in zenodo

mapping:
   - target_key: //title
     source_key: title
   - target_key: //description
     source_key: description
   - target_key: //contributors/0/name
     source_key: contributors[*].contributorName
     priority: 2
   - target_key: //contributors/0/orcid
     source_key: contributors[*].contributorId
   - target_key: //contributors/0/affiliation
     source_key: contributors[*].contributorAffiliation
   - target_key: //contributors/0/type
     target_key_values: [ "ContactPerson", "DataCollector", "DataCurator", "DataManager","Distributor", "Editor", "HostingInstitution", "Producer", "ProjectLeader", "ProjectManager", "ProjectMember", "RegistrationAgency", "RegistrationAuthority", "RelatedPerson", "Researcher", "ResearchGroup", "RightsHolder","Supervisor", "Sponsor", "WorkPackageLeader", "Other" ]
     source_key: contact[*].contributorRole   
   - target_key: //creators/0/name
     source_key: contributors[*].contributorName
     priority: 2
   - target_key: //creators/0/orcid
     source_key: contributors[*].contributorId
   - target_key: //creators/0/affiliation
     source_key: contributors[*].contributorAffiliation
   - target_key: //subjects/0/term
     source_key: keywords[*]
     priority: 2
   - target_key: //keywords
     source_key: keywords[*]
     priority: 2
   - target_key: //related_identifiers/0/scheme
     source_key: relatedId[*].scheme
   - target_key: //related_identifiers/0/identifier
     source_key: relatedId[*].id
   - target_key: //related_identifiers/0/relation
     source_key: relatedId[*].relationType
   - target_key: //related_identifiers/0/resource_type
     source_key: relatedId[*].resourceType
   - target_key: //contributors/0/name
     source_key: contributors[*].contributorName
   - target_key: //contributors/0/type
     source_key: contributors[*].contributorRole
